// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: proto/codepix/transaction/read/stream.proto

package read

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nacks []bool `protobuf:"varint,1,rep,packed,name=nacks,proto3" json:"nacks,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetNacks() []bool {
	if x != nil {
		return x.Nacks
	}
	return nil
}

type StartedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender       []byte                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderBank   []byte                 `protobuf:"bytes,4,opt,name=sender_bank,json=senderBank,proto3" json:"sender_bank,omitempty"`
	Receiver     []byte                 `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	ReceiverBank []byte                 `protobuf:"bytes,6,opt,name=receiver_bank,json=receiverBank,proto3" json:"receiver_bank,omitempty"`
	Amount       uint64                 `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Description  string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *StartedTransaction) Reset() {
	*x = StartedTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartedTransaction) ProtoMessage() {}

func (x *StartedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartedTransaction.ProtoReflect.Descriptor instead.
func (*StartedTransaction) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StartedTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *StartedTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StartedTransaction) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *StartedTransaction) GetSenderBank() []byte {
	if x != nil {
		return x.SenderBank
	}
	return nil
}

func (x *StartedTransaction) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *StartedTransaction) GetReceiverBank() []byte {
	if x != nil {
		return x.ReceiverBank
	}
	return nil
}

func (x *StartedTransaction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StartedTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StartedTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*StartedTransaction `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *StartedTransactions) Reset() {
	*x = StartedTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartedTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartedTransactions) ProtoMessage() {}

func (x *StartedTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartedTransactions.ProtoReflect.Descriptor instead.
func (*StartedTransactions) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StartedTransactions) GetEvents() []*StartedTransaction {
	if x != nil {
		return x.Events
	}
	return nil
}

type ConfirmedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ConfirmedTransaction) Reset() {
	*x = ConfirmedTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedTransaction) ProtoMessage() {}

func (x *ConfirmedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedTransaction.ProtoReflect.Descriptor instead.
func (*ConfirmedTransaction) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmedTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ConfirmedTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ConfirmedTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*ConfirmedTransaction `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *ConfirmedTransactions) Reset() {
	*x = ConfirmedTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmedTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedTransactions) ProtoMessage() {}

func (x *ConfirmedTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedTransactions.ProtoReflect.Descriptor instead.
func (*ConfirmedTransactions) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmedTransactions) GetEvents() []*ConfirmedTransaction {
	if x != nil {
		return x.Events
	}
	return nil
}

type CompletedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *CompletedTransaction) Reset() {
	*x = CompletedTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedTransaction) ProtoMessage() {}

func (x *CompletedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedTransaction.ProtoReflect.Descriptor instead.
func (*CompletedTransaction) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{5}
}

func (x *CompletedTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CompletedTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CompletedTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*CompletedTransaction `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *CompletedTransactions) Reset() {
	*x = CompletedTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletedTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedTransactions) ProtoMessage() {}

func (x *CompletedTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedTransactions.ProtoReflect.Descriptor instead.
func (*CompletedTransactions) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{6}
}

func (x *CompletedTransactions) GetEvents() []*CompletedTransaction {
	if x != nil {
		return x.Events
	}
	return nil
}

type FailedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reason    string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *FailedTransaction) Reset() {
	*x = FailedTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedTransaction) ProtoMessage() {}

func (x *FailedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedTransaction.ProtoReflect.Descriptor instead.
func (*FailedTransaction) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{7}
}

func (x *FailedTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FailedTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FailedTransaction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type FailedTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*FailedTransaction `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *FailedTransactions) Reset() {
	*x = FailedTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailedTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedTransactions) ProtoMessage() {}

func (x *FailedTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codepix_transaction_read_stream_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedTransactions.ProtoReflect.Descriptor instead.
func (*FailedTransactions) Descriptor() ([]byte, []int) {
	return file_proto_codepix_transaction_read_stream_proto_rawDescGZIP(), []int{8}
}

func (x *FailedTransactions) GetEvents() []*FailedTransaction {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_codepix_transaction_read_stream_proto protoreflect.FileDescriptor

var file_proto_codepix_transaction_read_stream_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x61, 0x64,
	0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63,
	0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x05,
	0x6e, 0x61, 0x63, 0x6b, 0x73, 0x22, 0x92, 0x02, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x61, 0x6e, 0x6b, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x42, 0x61, 0x6e, 0x6b,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5b, 0x0a, 0x13, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x44, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x60, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5f, 0x0a, 0x15, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x60, 0x0a, 0x14, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5f, 0x0a, 0x15,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x64,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x75, 0x0a,
	0x11, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x12, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x43, 0x0a, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x64,
	0x65, 0x70, 0x69, 0x78, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x32,
	0x8a, 0x03, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x5d, 0x0a, 0x07, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x64,
	0x2e, 0x41, 0x63, 0x6b, 0x1a, 0x2d, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x64, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x61, 0x0a, 0x09, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61,
	0x64, 0x2e, 0x41, 0x63, 0x6b, 0x1a, 0x2f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x64,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x61, 0x0a, 0x09,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x70, 0x69, 0x78, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x72, 0x65, 0x61, 0x64, 0x2e, 0x41, 0x63, 0x6b, 0x1a, 0x2f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70,
	0x69, 0x78, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72,
	0x65, 0x61, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x5b, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x70, 0x69, 0x78, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x72, 0x65, 0x61, 0x64, 0x2e, 0x41, 0x63, 0x6b, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x70,
	0x69, 0x78, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72,
	0x65, 0x61, 0x64, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x31, 0x5a, 0x2f,
	0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x61, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_codepix_transaction_read_stream_proto_rawDescOnce sync.Once
	file_proto_codepix_transaction_read_stream_proto_rawDescData = file_proto_codepix_transaction_read_stream_proto_rawDesc
)

func file_proto_codepix_transaction_read_stream_proto_rawDescGZIP() []byte {
	file_proto_codepix_transaction_read_stream_proto_rawDescOnce.Do(func() {
		file_proto_codepix_transaction_read_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_codepix_transaction_read_stream_proto_rawDescData)
	})
	return file_proto_codepix_transaction_read_stream_proto_rawDescData
}

var file_proto_codepix_transaction_read_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_codepix_transaction_read_stream_proto_goTypes = []interface{}{
	(*Ack)(nil),                   // 0: codepix.transaction.read.Ack
	(*StartedTransaction)(nil),    // 1: codepix.transaction.read.StartedTransaction
	(*StartedTransactions)(nil),   // 2: codepix.transaction.read.StartedTransactions
	(*ConfirmedTransaction)(nil),  // 3: codepix.transaction.read.ConfirmedTransaction
	(*ConfirmedTransactions)(nil), // 4: codepix.transaction.read.ConfirmedTransactions
	(*CompletedTransaction)(nil),  // 5: codepix.transaction.read.CompletedTransaction
	(*CompletedTransactions)(nil), // 6: codepix.transaction.read.CompletedTransactions
	(*FailedTransaction)(nil),     // 7: codepix.transaction.read.FailedTransaction
	(*FailedTransactions)(nil),    // 8: codepix.transaction.read.FailedTransactions
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_codepix_transaction_read_stream_proto_depIdxs = []int32{
	9,  // 0: codepix.transaction.read.StartedTransaction.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: codepix.transaction.read.StartedTransactions.events:type_name -> codepix.transaction.read.StartedTransaction
	9,  // 2: codepix.transaction.read.ConfirmedTransaction.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 3: codepix.transaction.read.ConfirmedTransactions.events:type_name -> codepix.transaction.read.ConfirmedTransaction
	9,  // 4: codepix.transaction.read.CompletedTransaction.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 5: codepix.transaction.read.CompletedTransactions.events:type_name -> codepix.transaction.read.CompletedTransaction
	9,  // 6: codepix.transaction.read.FailedTransaction.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 7: codepix.transaction.read.FailedTransactions.events:type_name -> codepix.transaction.read.FailedTransaction
	0,  // 8: codepix.transaction.read.Stream.Started:input_type -> codepix.transaction.read.Ack
	0,  // 9: codepix.transaction.read.Stream.Confirmed:input_type -> codepix.transaction.read.Ack
	0,  // 10: codepix.transaction.read.Stream.Completed:input_type -> codepix.transaction.read.Ack
	0,  // 11: codepix.transaction.read.Stream.Failed:input_type -> codepix.transaction.read.Ack
	2,  // 12: codepix.transaction.read.Stream.Started:output_type -> codepix.transaction.read.StartedTransactions
	4,  // 13: codepix.transaction.read.Stream.Confirmed:output_type -> codepix.transaction.read.ConfirmedTransactions
	6,  // 14: codepix.transaction.read.Stream.Completed:output_type -> codepix.transaction.read.CompletedTransactions
	8,  // 15: codepix.transaction.read.Stream.Failed:output_type -> codepix.transaction.read.FailedTransactions
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_codepix_transaction_read_stream_proto_init() }
func file_proto_codepix_transaction_read_stream_proto_init() {
	if File_proto_codepix_transaction_read_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_codepix_transaction_read_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartedTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartedTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmedTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmedTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletedTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletedTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailedTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codepix_transaction_read_stream_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailedTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_codepix_transaction_read_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_codepix_transaction_read_stream_proto_goTypes,
		DependencyIndexes: file_proto_codepix_transaction_read_stream_proto_depIdxs,
		MessageInfos:      file_proto_codepix_transaction_read_stream_proto_msgTypes,
	}.Build()
	File_proto_codepix_transaction_read_stream_proto = out.File
	file_proto_codepix_transaction_read_stream_proto_rawDesc = nil
	file_proto_codepix_transaction_read_stream_proto_goTypes = nil
	file_proto_codepix_transaction_read_stream_proto_depIdxs = nil
}
