apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: codepix-bank-api
spec:
  type: LoadBalancer
  ports:
    - port: 4000
  selector:
    name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: codepix-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api
          image: registry.codepix.local/bank-api:latest
          ports:
            - containerPort: 4000
          resources: {}
          envFrom:
            - configMapRef:
                name: api
            - secretRef:
                name: api
            - configMapRef:
                name: database
            - secretRef:
                name: database
