// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: bank-api/transaction/stream/proto/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Started *TransactionStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof" json:"started,omitempty"`
	Error   *TransactionError   `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *StartedOut) Reset() {
	*x = StartedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartedOut) ProtoMessage() {}

func (x *StartedOut) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartedOut.ProtoReflect.Descriptor instead.
func (*StartedOut) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *StartedOut) GetStarted() *TransactionStarted {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *StartedOut) GetError() *TransactionError {
	if x != nil {
		return x.Error
	}
	return nil
}

type StartedIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: validate:"excluded_with=fail"
	Confirm *ConfirmTransaction `protobuf:"bytes,1,opt,name=confirm,proto3,oneof" json:"confirm,omitempty" validate:"excluded_with=fail"`
	// @gotags: validate:"excluded_with=confirm"
	Fail *FailTransaction `protobuf:"bytes,2,opt,name=fail,proto3,oneof" json:"fail,omitempty" validate:"excluded_with=confirm"`
}

func (x *StartedIn) Reset() {
	*x = StartedIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartedIn) ProtoMessage() {}

func (x *StartedIn) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartedIn.ProtoReflect.Descriptor instead.
func (*StartedIn) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *StartedIn) GetConfirm() *ConfirmTransaction {
	if x != nil {
		return x.Confirm
	}
	return nil
}

func (x *StartedIn) GetFail() *FailTransaction {
	if x != nil {
		return x.Fail
	}
	return nil
}

type ConfirmedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirmed *TransactionConfirmed `protobuf:"bytes,1,opt,name=confirmed,proto3,oneof" json:"confirmed,omitempty"`
	Error     *TransactionError     `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *ConfirmedOut) Reset() {
	*x = ConfirmedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedOut) ProtoMessage() {}

func (x *ConfirmedOut) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedOut.ProtoReflect.Descriptor instead.
func (*ConfirmedOut) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmedOut) GetConfirmed() *TransactionConfirmed {
	if x != nil {
		return x.Confirmed
	}
	return nil
}

func (x *ConfirmedOut) GetError() *TransactionError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ConfirmedIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: validate:"excluded_with=fail"
	Complete *CompleteTransaction `protobuf:"bytes,1,opt,name=complete,proto3,oneof" json:"complete,omitempty" validate:"excluded_with=fail"`
	// @gotags: validate:"excluded_with=complete"
	Fail *FailTransaction `protobuf:"bytes,2,opt,name=fail,proto3,oneof" json:"fail,omitempty" validate:"excluded_with=complete"`
}

func (x *ConfirmedIn) Reset() {
	*x = ConfirmedIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmedIn) ProtoMessage() {}

func (x *ConfirmedIn) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmedIn.ProtoReflect.Descriptor instead.
func (*ConfirmedIn) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmedIn) GetComplete() *CompleteTransaction {
	if x != nil {
		return x.Complete
	}
	return nil
}

func (x *ConfirmedIn) GetFail() *FailTransaction {
	if x != nil {
		return x.Fail
	}
	return nil
}

// out
type TransactionStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReceiverAccountNumber string `protobuf:"bytes,4,opt,name=receiver_account_number,json=receiverAccountNumber,proto3" json:"receiver_account_number,omitempty"`
	Amount                uint64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Description           string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *TransactionStarted) Reset() {
	*x = TransactionStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStarted) ProtoMessage() {}

func (x *TransactionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStarted.ProtoReflect.Descriptor instead.
func (*TransactionStarted) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionStarted) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TransactionStarted) GetReceiverAccountNumber() string {
	if x != nil {
		return x.ReceiverAccountNumber
	}
	return ""
}

func (x *TransactionStarted) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionStarted) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransactionConfirmed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TransactionConfirmed) Reset() {
	*x = TransactionConfirmed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionConfirmed) ProtoMessage() {}

func (x *TransactionConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionConfirmed.ProtoReflect.Descriptor instead.
func (*TransactionConfirmed) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionConfirmed) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type TransactionError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TransactionError) Reset() {
	*x = TransactionError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionError) ProtoMessage() {}

func (x *TransactionError) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionError.ProtoReflect.Descriptor instead.
func (*TransactionError) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionError) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TransactionError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TransactionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// in
type ConfirmTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"` // @gotags: validate:"required"
}

func (x *ConfirmTransaction) Reset() {
	*x = ConfirmTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTransaction) ProtoMessage() {}

func (x *ConfirmTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTransaction.ProtoReflect.Descriptor instead.
func (*ConfirmTransaction) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type CompleteTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"` // @gotags: validate:"required"
}

func (x *CompleteTransaction) Reset() {
	*x = CompleteTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTransaction) ProtoMessage() {}

func (x *CompleteTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTransaction.ProtoReflect.Descriptor instead.
func (*CompleteTransaction) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type FailTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"`         // @gotags: validate:"required"
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty" validate:"max=100" mod:"trim"` // @gotags: validate:"max=100" mod:"trim"
}

func (x *FailTransaction) Reset() {
	*x = FailTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTransaction) ProtoMessage() {}

func (x *FailTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTransaction.ProtoReflect.Descriptor instead.
func (*FailTransaction) Descriptor() ([]byte, []int) {
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *FailTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FailTransaction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_bank_api_transaction_stream_proto_transaction_proto protoreflect.FileDescriptor

var file_bank_api_transaction_stream_proto_transaction_proto_rawDesc = []byte{
	0x0a, 0x33, 0x62, 0x61, 0x6e, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x75,
	0x74, 0x12, 0x3e, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x38, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x01, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x12,
	0x3e, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x88, 0x01, 0x01, 0x12,
	0x35, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x61, 0x69, 0x6c,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x04, 0x66,
	0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x22, 0xa6, 0x01, 0x0a, 0x0c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x44, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x38, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x01, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x65, 0x64, 0x49, 0x6e, 0x12, 0x41, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x66, 0x61, 0x69, 0x6c, 0x22, 0x96, 0x01, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x26, 0x0a,
	0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a,
	0x13, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x0f, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32,
	0x9d, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x40, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x16, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x1a, 0x17, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x75,
	0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x65, 0x64, 0x12, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x49, 0x6e, 0x1a, 0x19,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x2a, 0x5a, 0x28, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x69, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bank_api_transaction_stream_proto_transaction_proto_rawDescOnce sync.Once
	file_bank_api_transaction_stream_proto_transaction_proto_rawDescData = file_bank_api_transaction_stream_proto_transaction_proto_rawDesc
)

func file_bank_api_transaction_stream_proto_transaction_proto_rawDescGZIP() []byte {
	file_bank_api_transaction_stream_proto_transaction_proto_rawDescOnce.Do(func() {
		file_bank_api_transaction_stream_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_bank_api_transaction_stream_proto_transaction_proto_rawDescData)
	})
	return file_bank_api_transaction_stream_proto_transaction_proto_rawDescData
}

var file_bank_api_transaction_stream_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bank_api_transaction_stream_proto_transaction_proto_goTypes = []interface{}{
	(*StartedOut)(nil),           // 0: transaction.StartedOut
	(*StartedIn)(nil),            // 1: transaction.StartedIn
	(*ConfirmedOut)(nil),         // 2: transaction.ConfirmedOut
	(*ConfirmedIn)(nil),          // 3: transaction.ConfirmedIn
	(*TransactionStarted)(nil),   // 4: transaction.TransactionStarted
	(*TransactionConfirmed)(nil), // 5: transaction.TransactionConfirmed
	(*TransactionError)(nil),     // 6: transaction.TransactionError
	(*ConfirmTransaction)(nil),   // 7: transaction.ConfirmTransaction
	(*CompleteTransaction)(nil),  // 8: transaction.CompleteTransaction
	(*FailTransaction)(nil),      // 9: transaction.FailTransaction
}
var file_bank_api_transaction_stream_proto_transaction_proto_depIdxs = []int32{
	4,  // 0: transaction.StartedOut.started:type_name -> transaction.TransactionStarted
	6,  // 1: transaction.StartedOut.error:type_name -> transaction.TransactionError
	7,  // 2: transaction.StartedIn.confirm:type_name -> transaction.ConfirmTransaction
	9,  // 3: transaction.StartedIn.fail:type_name -> transaction.FailTransaction
	5,  // 4: transaction.ConfirmedOut.confirmed:type_name -> transaction.TransactionConfirmed
	6,  // 5: transaction.ConfirmedOut.error:type_name -> transaction.TransactionError
	8,  // 6: transaction.ConfirmedIn.complete:type_name -> transaction.CompleteTransaction
	9,  // 7: transaction.ConfirmedIn.fail:type_name -> transaction.FailTransaction
	1,  // 8: transaction.TransactionStream.Started:input_type -> transaction.StartedIn
	3,  // 9: transaction.TransactionStream.Confirmed:input_type -> transaction.ConfirmedIn
	0,  // 10: transaction.TransactionStream.Started:output_type -> transaction.StartedOut
	2,  // 11: transaction.TransactionStream.Confirmed:output_type -> transaction.ConfirmedOut
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bank_api_transaction_stream_proto_transaction_proto_init() }
func file_bank_api_transaction_stream_proto_transaction_proto_init() {
	if File_bank_api_transaction_stream_proto_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartedIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmedIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionConfirmed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_bank_api_transaction_stream_proto_transaction_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bank_api_transaction_stream_proto_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_api_transaction_stream_proto_transaction_proto_goTypes,
		DependencyIndexes: file_bank_api_transaction_stream_proto_transaction_proto_depIdxs,
		MessageInfos:      file_bank_api_transaction_stream_proto_transaction_proto_msgTypes,
	}.Build()
	File_bank_api_transaction_stream_proto_transaction_proto = out.File
	file_bank_api_transaction_stream_proto_transaction_proto_rawDesc = nil
	file_bank_api_transaction_stream_proto_transaction_proto_goTypes = nil
	file_bank_api_transaction_stream_proto_transaction_proto_depIdxs = nil
}
