// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: bank-api/transaction/stream/proto/transaction.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionStreamClient is the client API for TransactionStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionStreamClient interface {
	Started(ctx context.Context, opts ...grpc.CallOption) (TransactionStream_StartedClient, error)
	Confirmed(ctx context.Context, opts ...grpc.CallOption) (TransactionStream_ConfirmedClient, error)
}

type transactionStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionStreamClient(cc grpc.ClientConnInterface) TransactionStreamClient {
	return &transactionStreamClient{cc}
}

func (c *transactionStreamClient) Started(ctx context.Context, opts ...grpc.CallOption) (TransactionStream_StartedClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionStream_ServiceDesc.Streams[0], "/transaction.TransactionStream/Started", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionStreamStartedClient{stream}
	return x, nil
}

type TransactionStream_StartedClient interface {
	Send(*StartedIn) error
	Recv() (*StartedOut, error)
	grpc.ClientStream
}

type transactionStreamStartedClient struct {
	grpc.ClientStream
}

func (x *transactionStreamStartedClient) Send(m *StartedIn) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionStreamStartedClient) Recv() (*StartedOut, error) {
	m := new(StartedOut)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionStreamClient) Confirmed(ctx context.Context, opts ...grpc.CallOption) (TransactionStream_ConfirmedClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionStream_ServiceDesc.Streams[1], "/transaction.TransactionStream/Confirmed", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionStreamConfirmedClient{stream}
	return x, nil
}

type TransactionStream_ConfirmedClient interface {
	Send(*ConfirmedIn) error
	Recv() (*ConfirmedOut, error)
	grpc.ClientStream
}

type transactionStreamConfirmedClient struct {
	grpc.ClientStream
}

func (x *transactionStreamConfirmedClient) Send(m *ConfirmedIn) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionStreamConfirmedClient) Recv() (*ConfirmedOut, error) {
	m := new(ConfirmedOut)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionStreamServer is the server API for TransactionStream service.
// All implementations must embed UnimplementedTransactionStreamServer
// for forward compatibility
type TransactionStreamServer interface {
	Started(TransactionStream_StartedServer) error
	Confirmed(TransactionStream_ConfirmedServer) error
	mustEmbedUnimplementedTransactionStreamServer()
}

// UnimplementedTransactionStreamServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionStreamServer struct {
}

func (UnimplementedTransactionStreamServer) Started(TransactionStream_StartedServer) error {
	return status.Errorf(codes.Unimplemented, "method Started not implemented")
}
func (UnimplementedTransactionStreamServer) Confirmed(TransactionStream_ConfirmedServer) error {
	return status.Errorf(codes.Unimplemented, "method Confirmed not implemented")
}
func (UnimplementedTransactionStreamServer) mustEmbedUnimplementedTransactionStreamServer() {}

// UnsafeTransactionStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionStreamServer will
// result in compilation errors.
type UnsafeTransactionStreamServer interface {
	mustEmbedUnimplementedTransactionStreamServer()
}

func RegisterTransactionStreamServer(s grpc.ServiceRegistrar, srv TransactionStreamServer) {
	s.RegisterService(&TransactionStream_ServiceDesc, srv)
}

func _TransactionStream_Started_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionStreamServer).Started(&transactionStreamStartedServer{stream})
}

type TransactionStream_StartedServer interface {
	Send(*StartedOut) error
	Recv() (*StartedIn, error)
	grpc.ServerStream
}

type transactionStreamStartedServer struct {
	grpc.ServerStream
}

func (x *transactionStreamStartedServer) Send(m *StartedOut) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionStreamStartedServer) Recv() (*StartedIn, error) {
	m := new(StartedIn)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TransactionStream_Confirmed_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionStreamServer).Confirmed(&transactionStreamConfirmedServer{stream})
}

type TransactionStream_ConfirmedServer interface {
	Send(*ConfirmedOut) error
	Recv() (*ConfirmedIn, error)
	grpc.ServerStream
}

type transactionStreamConfirmedServer struct {
	grpc.ServerStream
}

func (x *transactionStreamConfirmedServer) Send(m *ConfirmedOut) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionStreamConfirmedServer) Recv() (*ConfirmedIn, error) {
	m := new(ConfirmedIn)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionStream_ServiceDesc is the grpc.ServiceDesc for TransactionStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionStream",
	HandlerType: (*TransactionStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Started",
			Handler:       _TransactionStream_Started_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Confirmed",
			Handler:       _TransactionStream_Confirmed_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bank-api/transaction/stream/proto/transaction.proto",
}
