@host = http://localhost:5000
@api = {{host}}/api

@email = customer@example.com

# @name start_signup
POST {{api}}/signup-request

{
  "name": "test",
  "email": "{{email}}"
}
###

# @name finish_signup
# @prompt signup_token the token sent via email
POST {{api}}/signup-request/{{signup_token}}
###

# @name start_signin
POST {{api}}/signin-request

{
  "email": "{{email}}"
}
###

# @name finish_signin
# @prompt signin_token the token sent via email
POST {{api}}/signin-request/{{signin_token}}
###

@cookie = {{finish_signin.response.headers.Set-Cookie}}
@customer_id = {{finish_signin.response.body.customer_id}}

# @name find_customer
GET {{api}}/customer/{{customer_id}}
Cookie: {{cookie}}
###

# @name register_account
POST {{api}}/account
Cookie: {{cookie}}
###

@account_id = {{register_account.response.body.id}}

# @name find_account
GET {{api}}/account/{{account_id}}
Cookie: {{cookie}}
###

# @name remove_account
DELETE {{api}}/account/{{account_id}}
Cookie: {{cookie}}
###

# @name list_accounts
GET {{api}}/customer/{{customer_id}}/accounts
Cookie: {{cookie}}
###
