// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: bank-api/pixkey/service/proto/pixkey.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PixKeyServiceClient is the client API for PixKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PixKeyServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindReply, error)
}

type pixKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPixKeyServiceClient(cc grpc.ClientConnInterface) PixKeyServiceClient {
	return &pixKeyServiceClient{cc}
}

func (c *pixKeyServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/pixkey.PixKeyService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pixKeyServiceClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindReply, error) {
	out := new(FindReply)
	err := c.cc.Invoke(ctx, "/pixkey.PixKeyService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PixKeyServiceServer is the server API for PixKeyService service.
// All implementations must embed UnimplementedPixKeyServiceServer
// for forward compatibility
type PixKeyServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	Find(context.Context, *FindRequest) (*FindReply, error)
	mustEmbedUnimplementedPixKeyServiceServer()
}

// UnimplementedPixKeyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPixKeyServiceServer struct {
}

func (UnimplementedPixKeyServiceServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPixKeyServiceServer) Find(context.Context, *FindRequest) (*FindReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedPixKeyServiceServer) mustEmbedUnimplementedPixKeyServiceServer() {}

// UnsafePixKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PixKeyServiceServer will
// result in compilation errors.
type UnsafePixKeyServiceServer interface {
	mustEmbedUnimplementedPixKeyServiceServer()
}

func RegisterPixKeyServiceServer(s grpc.ServiceRegistrar, srv PixKeyServiceServer) {
	s.RegisterService(&PixKeyService_ServiceDesc, srv)
}

func _PixKeyService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixKeyServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pixkey.PixKeyService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixKeyServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PixKeyService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PixKeyServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pixkey.PixKeyService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PixKeyServiceServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PixKeyService_ServiceDesc is the grpc.ServiceDesc for PixKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PixKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pixkey.PixKeyService",
	HandlerType: (*PixKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PixKeyService_Register_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _PixKeyService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank-api/pixkey/service/proto/pixkey.proto",
}
